### ISSUE TITLE
Элемент списка RSS-лент изменяется в высоте в режиме редактирования

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#1]
![2019-07-14_15-35-29](https://user-images.githubusercontent.com/15068331/61183714-457ca500-a64d-11e9-8678-a3c33b7f087d.png)
![2019-07-14_15-35-43](https://user-images.githubusercontent.com/15068331/61183718-47deff00-a64d-11e9-8268-4944237a8bd2.png)
Это ужасно(

**Comment by Dasha6elka** [comment]
Поправила
