### ISSUE TITLE
Упрощение кода с помощью готовых компонентов Material UI

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#11]
Приведу пример.
У тебя разметка всё же осталась с прямым использованием CSS. Есть компонент Grid, который позволяет сделать всё почти без CSS:
![изображение](https://user-images.githubusercontent.com/15068331/61184808-8cbd6280-a65a-11e9-829b-02bd0a0d31d0.png)
![изображение](https://user-images.githubusercontent.com/15068331/61184851-f8073480-a65a-11e9-8a75-3fe23b7baad9.png)
![изображение](https://user-images.githubusercontent.com/15068331/61184859-07867d80-a65b-11e9-96db-367f50c3abad.png)
![изображение](https://user-images.githubusercontent.com/15068331/61184864-12411280-a65b-11e9-84a8-484409d12654.png)
Выглядит вроде бы также:
![изображение](https://user-images.githubusercontent.com/15068331/61184874-2ab12d00-a65b-11e9-9db7-49044fdd732a.png)

По Diff'у видно, что кода приубавилось чуток, и это я лишь самый-самый верх структуры приложения заменил. Надо везде так же. Как можно меньше CSS, как можно меньше не Material UI компонент =)

**Comment by Relz** [comment]
Вот ещё пример, как уменьшили css в пользу готовых конструкций.
Панель фильтрации выглядела так:
![2019-07-26_14-26-00](https://user-images.githubusercontent.com/15068331/61950560-eefd5800-afb6-11e9-85e1-1768cb62b2d2.png)
Применяем магию:
![2019-07-26_15-04-14](https://user-images.githubusercontent.com/15068331/61950575-ffadce00-afb6-11e9-9a52-1b0ed5e80b08.png)
Теперь выглядит так:
![2019-07-26_15-04-59](https://user-images.githubusercontent.com/15068331/61950583-05a3af00-afb7-11e9-83ad-b735c8c13b30.png)

**Comment by Relz** [comment]
Предлагаю взглянуть на все места, где есть css и постараться вместо него использовать что-то из библиотеки. Вот взять этот пример выше:
У тебя была задача поместить иконку слева от поля ввода. Ты сделала relative контейнер с нужными паддингами, в нём поле ввода с отступом, достаточным для того, чтобы вместилась иконка, а самой иконке говоришь position: absolute с нужным отступом. Не кажется, что это какая-то жесть? Целый ритуал)
А теперь же у нас всё куда проще:
контейнер с нужными паддингами, в нём поле ввода, у которого указываем, что в начале должна быть иконка.
Занавес!

**Comment by Relz** [comment]
![2019-08-01_14-49-47](https://user-images.githubusercontent.com/15068331/62291113-a5f04c80-b46b-11e9-9c6e-42fb6fafe2a6.png)
```js
/** @jsx jsx */

import { css, jsx } from "@emotion/core";
import { Grid } from "@material-ui/core";
import Typography from "@material-ui/core/Typography";

function Prompt(props) {
  return (
    <Grid container direction={"column"} alignItems={"center"}>
      <img
        src={props.url}
        alt=""
        css={css`
          max-height: ${props.height};
          max-width: ${props.width};
          margin: 20px auto;
        `}
      />
      <Typography css={css`color: dimgrey;`}>{props.text}</Typography>
    </Grid>
  );
}

export default Prompt;
```

**Comment by Relz** [comment]
Если так сделать, то логика же останется прежней? При этом логика проще (без условий)
![2019-08-01_15-13-09](https://user-images.githubusercontent.com/15068331/62292377-f3ba8400-b46e-11e9-9b75-b36544c52452.png)

**Comment by Dasha6elka** [comment]
Да

**Comment by Relz** [comment]
- [ ] width: 100% | display: block -> fullWidth у компонентов (например, Button и MaterialInput)

- [ ] text-align: center; у Button зачем?

- [ ] У элемента RSS-ссылки всё, кроме color в css-свойствах - зачем?

- [ ] ChannelTitle может быть либо текстом, либо Input'ом. Но у них есть дублирование стилей. Нужно вынести этот стиль

- [ ] У текста названия RSS-ленты min-height, text-overflow, overflow - зачем?

- [ ] У Input'а названия RSS-ленты max-height - зачем?

- [ ] width: auto; в "Удалить ленту" можно заменить на wrap="nowrap" аттрибут у Grid'ов + правильное выставление container и item
