### ISSUE TITLE
Упрощение onChannelItemEditFinish

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#16]
https://github.com/Dasha6elka/rss-reader/blob/b3547885813bacca8c5791faa227249a4e225070/src/containers/Channels.js#L28-L30
Вроде бы если просто channels.map(bla-bla-bla); оставить, то должно сработать, так как .map возвращает новый список

**Comment by Dasha6elka** [comment]
Исправила

**Comment by Relz** [comment]
Верю, но всё же запуш, повосхищаюсь)
