### ISSUE TITLE
Непонятный интерфейс при отсутствии каких-либо RSS-лент и категорий

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#19]
![изображение](https://user-images.githubusercontent.com/15068331/61811545-5944ba00-ae4a-11e9-83c4-149c9bfcf434.png)
Пользователь, который только начал работу с твоим сервисом, в первую очередь задастся вопросами:
- Что за пустые прямоугольники?
- Что за поле поиска и почему ничего не происходит, когда я ввожу там текст?
- Что происходит?

Нужно что-то придумать с этим. Интерфейс должен проявлять любовь, заботу и нежность по отношению к пользователям :)

**Comment by Dasha6elka** [comment]
+
