### ISSUE TITLE
Пустой Select выбора категории RSS-ленты

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#20]
Я, как новый пользователь, поманился на кнопку "Добавить ленту", так как она бросилась мне в глаза. Появилась форма, я начал её заполнять. Но при нажатии на Select выбора категории я увидел что-то дьявольски жуткое:
![изображение](https://user-images.githubusercontent.com/15068331/61812178-a8d7b580-ae4b-11e9-8934-f86fc0779fe3.png)

**Comment by Dasha6elka** [comment]
+
