### ISSUE TITLE
Невалидное имя ленты

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#21]
Заполняю форму добавления RSS-ленты. Решил добавить такую:
Имя: Medium: @dane.mackier
Ссылка: https://medium.com/feed/@dane.mackier
Но почему-то сервис не разрешает задать такое имя, говоря: "Невалидное имя ленты":
![изображение](https://user-images.githubusercontent.com/15068331/61812254-d02e8280-ae4b-11e9-9394-b987144a8227.png)
Не понимаю, что такого запретного в таком имени, и сервис даже не удосуживается показать, какие символы разрешены(

**Comment by Dasha6elka** [comment]
+
