### ISSUE TITLE
Warning: "Each child in a list should have a unique "key" prop."

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#22]
![изображение](https://user-images.githubusercontent.com/15068331/61812547-62cf2180-ae4c-11e9-86eb-e488ab5ffd1a.png)
Шаги для воспроизведения (способ 1):
1. Нажать на кнопку "Добавить ленту"
2. Нажать на кнопку "Новая категория"

Шаги для воспроизведения (способ 2):
1. Нажать на кнопку "Новая категория"
2. Нажать на кнопку "Добавить ленту"

**Comment by Dasha6elka** [comment]
+
