### ISSUE TITLE
Почему-то кнопка "Новая категория" не нажимается

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#23]
Здравствуйте! Я начинающий в вашей системе, столкнулся с трудностью добавления новой категории. Я нажал на кнопочку "Новая категория". Эта кнопочка скакнула вниз, вместо неё появилось какое-то поле ввода с иконкой удаления. Я нажал на "Новая категория" ещё раз, но она уже не нажимается. Я сломал вторую мышку, она всё равно не нажимается. Я ничего не понимаю. Памагити.
![изображение](https://user-images.githubusercontent.com/15068331/61812865-146e5280-ae4d-11e9-9495-3467e3eebf27.png)

**Comment by Dasha6elka** [comment]
+
