### ISSUE TITLE
Омагад! Омагад! Скример!

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#24]
Здравствуйте! Я впечатлительный хаброфил. Я добавил категорию "Программирование", в неё пытался добавить ленту habr'а, но при нажатии на кнопку "Добавить" упал со стула от испуга:
![изображение](https://user-images.githubusercontent.com/15068331/61813206-d9205380-ae4d-11e9-9596-beb88c1fafd2.png)

**Comment by Dasha6elka** [comment]
+
