### ISSUE TITLE
Куда-то пропадают RSS-ленты текущей категории при заполнении формы добавления RSS-ленты

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#25]
Здрасьте! У меня в категории "Программирование" есть лента хабра. Она показывается в списке, всё круто:
![изображение](https://user-images.githubusercontent.com/15068331/61813462-6b285c00-ae4e-11e9-9d18-f3e34b9d84fb.png)
Затем я решил добавить ещё одну ленту. Задаю имя и бам! Нет списка лент:
![изображение](https://user-images.githubusercontent.com/15068331/61813512-885d2a80-ae4e-11e9-97a6-9c916246b22c.png)

**Comment by Dasha6elka** [comment]
👍
