### ISSUE TITLE
Лента добавилась в список до завершения заполнения формы

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#26]
Магия какая-то:
![Лента добавилась в список до завершения заполнения формы](https://user-images.githubusercontent.com/15068331/61814452-cc512f00-ae50-11e9-9f30-69fbe2f4941e.gif)
Я ещё не нажал на "Добавить", а она уже в списке, и в реал-тайме название меняется. Толи баг, толи фича)

**Comment by Dasha6elka** [comment]
👍
