### ISSUE TITLE
Рефакторинг функции onChannelDelete (Channels.js:13)

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#29]
- [x] Не понятно, почему мы принимаем в параметрах index и id. Зачем нам для удаления канала и индекс в неком списке и идентификатор удаляемого канала? Кажется, достаточно что-то одно.

- [x] Можно вынести дублирующие длинные обращения в переменную:
![2019-07-26_11-59-18](https://user-images.githubusercontent.com/15068331/61939860-e7c95080-af9c-11e9-926f-c86a2d1832f9.png)
кажется, можно назвать это "channelToDelete" и "channelToChange".
Дабы это было не похоже на просто "так надо", попробую объяснить этот момент:
Пусть у нас какой-то персонаж игры, хранится в списке всех персонажей, у него есть функция "съесть пищу", которая снизит его голод, повысит уровень жизни и улучшит настроение:
```js
function eatFood(playerIndex, food) {
    players[playerIndex].starvationLevel -= food.caloriesLevel;
    players[playerIndex].healthPoints += food.healthPoints;
    players[playerIndex].mood += food.moodLevel;
}
```
А теперь прочитаем эту функцию:
Функция "съесть пищу" принимает индекс игрока и пищу.
Уменьшаем уровень голода у игрока из списка игроков по индексу playerIndex на уровень калорийности пищи.
Увеличиваем очки жизни у игрока из списка игроков по индексу playerIndex на очки жизни пищи.
Увеличиваем настроение у игрока из списка игроков по индексу playerIndex на уровень настроения пищи.

А теперь вынесем общую часть в переменную:
```js
function eatFood(playerIndex, food) {
    const player = players[playerIndex];
    player.starvationLevel -= food.caloriesLevel;
    player.healthPoints += food.healthPoints;
    player.mood += food.moodLevel;
}
```
Функция "съесть пищу" принимает индекс игрока и пищу.
Берём игрока из списка игроков по индексу.
Уменьшаем его уровень голода на уровень калорийности пищи.
Увеличиваем его очки жизни на очки жизни пищи.
Увеличиваем его настроение на уровень настроения пищи.

- [ ] В конце метода вызывается onChannelDelete, затем onChannelsChange, при этом onChannelDelete вызывает setChannels, причём дважды, затем onChannelsChange выывает ещё один setChannels. То есть в итоге вызывается трижды. Зачем так?

**Comment by Dasha6elka** [comment]
👍
