### ISSUE TITLE
Не подсвечивается активный элемент списка категорий RSS-лент

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#3]
Судя по кол-ву лент, при первоначальной загрузке приложения показываются RSS-ленты из категории "Программирование", однако сам элемент списка никак не индицируется. По дизайну активный элемент имеет один стиль, а наведённое состояние индицируется по-другому:
![изображение](https://user-images.githubusercontent.com/15068331/61183789-2e8a8280-a64e-11e9-9384-71bace8503c8.png)

**Comment by Dasha6elka** [comment]
Поправила. При нажатии на категорию, она становится активной
