### ISSUE TITLE
Рефакторинг функции onChannelItemChange(Channels.js:30)

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#30]
Здесь проблема в том, что функция выполняет разные действия в зависимости от параметра. Пришли в голову 2 альтернативы:
1) Channel вызывает разные callback'и (onTitleChange и onLinkChange) вместо использования одного лишь onChange. Таким образом в Channels.js будут два трёх-строчных метода.
2) Channel вызывает onChange, но передаёт туда весь объект канала с полями title и link. Таким образом в Channels.js метод onChannelItemChange присвоит все поля, даже если какие-то из них не были реально изменены, но это не считается плохим подходом:
```js
function onChannelItemChange(index, newChannel) {
    const channelToChange = context.channels[index];
    channelToChange.editable = true;
    channelToChange.title = newChannel.title;
    channelToChange.rss_url = newChannel.rss_url;
    context.onChannelsChange([...context.channels]);
}
```

**Comment by Dasha6elka** [comment]
👍
