### ISSUE TITLE
Абстрактно названа функция onButtonClick(Sidebar.js:16) и onFormButtonClick(Sidebar.js:20)

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#34]
При виде данного названия и зная, что мы в файле Sidebar.js, я смог построить весьма скудное умозаключение: "Эта функция сработает при нажатии какой-то кнопки в Сайдбаре". Нужно назвать более конкретно. При этом ниже есть функция onFormButtonClick, которая чуть уточняет своё местоположение, но всё равно есть неопределённость, так как в средних формах не всегда одна кнопка фигурирует.

**Comment by Dasha6elka** [comment]
👍
