### ISSUE TITLE
Слово-паразит "data"

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#35]
https://github.com/Dasha6elka/rss-reader/blob/db73a9bf591d0c68365ab62d9e688a8948e8b709/src/containers/Sidebar.js#L77-L86
Слово "data"(данные) - это очень привлекательное слово для программистов, потому что подходит практически в каждом случае в силу своей абстрактности. В то же время абстрактность мешает человеку понять конкретность (капитан очевидность). Код будет намного понятнее, если таких абстрактностей будет как можно меньше.
В данной конкретной ситуации можно назвать аттрибут "items"... или "entries"... или "elements". Если верить гуглу, если List - тип данных в программировании, - то у него "elements", а если List - список в пользовательском интерфейсе, - то у него "items"

**Comment by Relz** [comment]
а entries я видел у типа данных Map (или Dictionary, если в C#) (или std::map, если в C++).

**Comment by Dasha6elka** [comment]
👍
