### ISSUE TITLE
Упростить выражения

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#37]
https://github.com/Dasha6elka/rss-reader/blob/db73a9bf591d0c68365ab62d9e688a8948e8b709/src/components/List.js#L18-L33

**Comment by Dasha6elka** [comment]
👍

**Comment by Relz** [comment]
Стало чуть лучше, но есть ещё ньюанс, очень похожий на математический пример:
a * b + c * d * b
Можно упростить

**Comment by Dasha6elka** [comment]
👍
