### ISSUE TITLE
Смешанные чувства от формы добавления RSS-ленты

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#4]
![изображение](https://user-images.githubusercontent.com/15068331/61183821-81643a00-a64e-11e9-9f51-10d29b2541b2.png)
Мне понравилось, что не открывается какое-нибудь всплывающее окно с формой, а всё происходит "не отходя от кассы". Однако есть и замечания:

- [x] Между поля ввода нет интервала. Это вызывает проблему только при фокусе какого-либо из полей:
![изображение](https://user-images.githubusercontent.com/15068331/61183848-e881ee80-a64e-11e9-86f6-fb0ac1a192f7.png)

- [x] Пусть категория выбирается из списка существующих с помощью компонента Select

- [x] Кнопку "Добавить" в Disabled-состоянии можно не заметить:
![2019-07-14_15-52-15](https://user-images.githubusercontent.com/15068331/61183903-b58c2a80-a64f-11e9-83ac-830690dba633.png)

- [x] Текст в полях ввода еле заметен
![изображение](https://user-images.githubusercontent.com/15068331/61184009-149e6f00-a651-11e9-842c-f7a0d0841d67.png)

- [x] Если выбрать имя ленты из предлагаемого списка, то поле ввода отличается от соседних. Да и вообще зачем предлагать там что-либо. Кажется, этим никто не будет пользоваться. Пусть вбивают без возникающих подсказок
![изображение](https://user-images.githubusercontent.com/15068331/61184009-149e6f00-a651-11e9-842c-f7a0d0841d67.png)

**Comment by Dasha6elka** [comment]
Исправила
