### ISSUE TITLE
Использовать встроенный метод строки "padStart"

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#40]
С одной стороны жалко, что крутую самописную функцию заставляют вырезать из кода, но с другой стороны это делегирование ответственности в продумывании и тестировании на других. У тебя функция:
https://github.com/Dasha6elka/rss-reader/blob/db73a9bf591d0c68365ab62d9e688a8948e8b709/src/components/Post.js#L96-L101
может быть заменена с помощью метода типа данных "string":
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

**Comment by Dasha6elka** [comment]
👍
