### ISSUE TITLE
Устранить дублирование кода в слое взаимодействия с сервером

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#41]
В директории src/api некоторые части кода повторяются, например headers в addCategory, addChannel, updateChannel. Нужно вынести куда-нибудь общий код

**Comment by Dasha6elka** [comment]
👍

**Comment by Relz** [comment]
RETURN_RESPONSE_TEXT - в итоге всё же больше функция, а не обычная константа, как API_URL, её ТАК_ИМЕНОВАТЬ_НЕ_НАДО.
И можно поместить файл constants.js в папку api, раз уж только там используются

**Comment by Relz** [comment]
https://github.com/Dasha6elka/rss-reader/blob/eca589df2d6abe5b759a73817fb8933b32cff52c/src/api/getCategories.js#L16-L22
Похоже на:
```js
if (expression) {
    action0();
    action1();
    action2();
} else {
    action0();
    action1();
    action3();
}
```
Но, может, явнее показывает, в чём проблема

**Comment by Dasha6elka** [comment]
👍  Не поместила файл constants.js в папку api, потому что использую этот файл также в файле App.js в папке containers

**Comment by Relz** [comment]
https://github.com/Dasha6elka/rss-reader/issues/41#issuecomment-515878685
Нужно устранить дублирование)

**Comment by Dasha6elka** [comment]
👍
