### ISSUE TITLE
Введите название поста

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#42]
![2019-07-26_14-14-55](https://user-images.githubusercontent.com/15068331/61948214-da699180-afaf-11e9-9d54-706cb4a592a0.png)
Но зачем я должен это делать? Не понятно. Даже при том, что у поле ввода есть иконка лупы, это может натолкнуть у австралопитека на как минимум 2 предположения:
1) "Я введу название поста, он будет искаться словно как в гугле, и я смогу его прочитать"
2) "Я введу название поста, тем самым быстрее найду его из списка"

**Comment by Dasha6elka** [comment]
хм
