### ISSUE TITLE
UX фильтрации при отсутствии статей

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#44]
![2019-07-29_10-47-18](https://user-images.githubusercontent.com/15068331/62030732-6537cf80-b1ee-11e9-9222-02c93d22bcae.png)
Тонкий момент UX: когда человек на что-нибудь нажимает, что-то вводит и ожидает, что что-то произойдёт - должно что-то происходить. Здесь же ничего не происходит, потому что технически нечему происходить, так как нечего фильтровать. Но это понимают только сверхразумы, типа тебя и твоего кота, например.
Можно избежать психологических травм пользователей, если, например, дизейблить поле ввода, если фильтровать нечего. На самом деле это не идеальный вариант, а скорее просто дешёво-приемлимый, так как есть минус: всё, что дизейблится, должно поясняться (нельзя задизейблить и не показать рядом какую-то подсказочку, мол почему задизейблено)

**Comment by Dasha6elka** [comment]
👍
