### ISSUE TITLE
Никому эти пустые полоски не нужны

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#45]
![2019-07-29_11-10-16](https://user-images.githubusercontent.com/15068331/62032212-cb722180-b1f1-11e9-91bc-41687fe3ae2b.png)
Я скролил список лент, а почему-то скролились все списки. На макете это не отражено, но это же очевидно! (с) типичный заказчик

**Comment by Dasha6elka** [comment]
👍
