### ISSUE TITLE
Нельзя удалить категорию с ненулевым количеством лент

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#46]
![2019-07-29_11-21-21](https://user-images.githubusercontent.com/15068331/62032710-058ff300-b1f3-11e9-99dc-9154ffd0cca0.png)
Краткость - сестра таланта. Чем больше людям приходится читать, тем больше приходится вдумываться в смысл.
Предлагаю что-то типа:
Нельзя удалить непустую категорию

**Comment by Relz** [comment]
А вообще странно, что меня заставляют сначала удалить все ленты в категории, а потом уже саму категорию. Почему программисты не могут сделать так, чтобы можно было удалить всю категорию одной кнопкой? 21 век, ну что за дела =(

**Comment by Dasha6elka** [comment]
👍
