### ISSUE TITLE
Обернуть ExpandLess и ExpandMore в Material UI компонент "IconButton"

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#49]
Если иконка нажимабельна, а не просто для отображения, то следует использовать её внутри IconButton, чтобы был визуальный эффект нажатия и наведения

**Comment by Dasha6elka** [comment]
👍

**Comment by Relz** [comment]
![2019-07-30_11-21-40](https://user-images.githubusercontent.com/15068331/62112884-44d64680-b2bc-11e9-9fad-08a6124b3424.png)
