### ISSUE TITLE
Стиль поле ввода новой категории

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#52]
![2019-07-30_11-00-47](https://user-images.githubusercontent.com/15068331/62111491-5d912d00-b2b9-11e9-92de-1febdfe238bf.png)
Как-то "приплюснуто". Можно уменьшить размер шрифта, чтобы было как у созданной категории? Скорее всего за счёт этого не будет выглядеть "приплюснуто"

**Comment by Dasha6elka** [comment]
👍
