### ISSUE TITLE
Empty white area for 15 sec before article is apeared

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#54]
Hello! I'm Purnama. I live in Indonesia and have slow internet speed.
I click to RSS-channel and then nothing is happening for 15 seconds. Can you add something like preloader, please?
![2019-07-30_11-19-48 (2)](https://user-images.githubusercontent.com/15068331/62112789-1ce6e300-b2bc-11e9-841e-386aebd87d2b.png)

**Comment by Dasha6elka** [comment]
👍

**Comment by Relz** [comment]
Из-за того что картинки загружаются со сторонних веб-ресурсов, они, бывает, медленно грузятся. В частности критично это выглядит в случае с "Загрузкой": пока эта картинка не загрузится, показывается "Жду", только в немного уменьшенном виде (под размеры "Загрузка"). Почему сразу не решила скачать эти картинки и сделать частью проекта? Так они загрузятся намного быстрее)

**Comment by Dasha6elka** [comment]
👍
