### ISSUE TITLE
Статьи остаются при смене на новосозданную категорию

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#55]
Создал категорию, добавил канал, загрузил список статей канала:
![2019-07-31_13-12-35](https://user-images.githubusercontent.com/15068331/62203969-e761f880-b394-11e9-9bee-cf1c07b00e9d.png)
Создаю новую категорию:
![2019-07-31_13-15-00 (2)](https://user-images.githubusercontent.com/15068331/62204152-49baf900-b395-11e9-9347-9f5f793f8105.png)

**Comment by Dasha6elka** [comment]
👍
