### ISSUE TITLE
Пустая иконка RSS-ленты какое-то время

### ISSUE THREAD

**Issue by Relz** [Dasha6elka/rss-reader#56]
![2019-07-31_13-17-29](https://user-images.githubusercontent.com/15068331/62204440-cd74e580-b395-11e9-8de4-3f3670c88a6e.png)
А потом она внезапно появляется. Конечно, иконка, это не такая критичная вещь, чтобы пользователь испытал недовольство. Но всё равно это как пятнышко на практически белой рубашке)
Как вариант, можно воспользоваться компонентом "CircularProgress" в Material UI

**Comment by Dasha6elka** [comment]
👍
